/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Toni García Vilche (https://sketchfab.com/zul_gv)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rusty-japanese-arcade-2938ae13a77c46e8afabb41eba18e699
Title: Rusty Japanese Arcade
*/
'use client'
import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';

const addSetupLighting = (model: THREE.Object3D) => {
    const ambient = new THREE.PointLight(0xff7E7922, .75, 2);
    ambient.position.set(0, 4, 0);
    model.add(ambient);

    const accent = new THREE.PointLight(0xff7E7922, .5, 1.5);
    accent.position.set(0, 1, 0);
    model.add(accent);
};


export function ArcadeMachine(scene : THREE.Scene, modalKey : string) {
    const loader = new GLTFLoader();

    // Helper: make a text texture for sprite
    const createTextCanvas = (text: string)  => {
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d')!;
        canvas.width = 512;
        canvas.height = 256;
        ctx.font = 'bold 90px Arial';
        ctx.fillStyle = '#000000';
        ctx.textAlign = 'center';
        ctx.textBaseline = 'middle';
        ctx.shadowColor = '#7E7922';
        ctx.shadowBlur = 15;
        ctx.fillText(text, canvas.width / 2, canvas.height / 2);
        return canvas;
    }

    return loader.load(
                'assets/3d/rusty_japanese_arcade.glb',
                (gltf) => {
                const arcadeModel = gltf.scene;

                // Position and scale (adjust as needed)
                arcadeModel.position.set(-5.40, 0, -5.290);
                arcadeModel.scale.set(.35, .35, .35);
                arcadeModel.rotation.y = Math.PI / 3;

                // Enable shadows for realism
                arcadeModel.traverse((child) => {
                    if ((child as THREE.Mesh).isMesh) {
                        child.castShadow = true;
                        child.receiveShadow = true;
                        child.userData.section = modalKey;
                    }
                });
                addSetupLighting(arcadeModel);

                // Add floating “Click Me” label
                const spriteMaterial = new THREE.SpriteMaterial({
                    map: new THREE.CanvasTexture(createTextCanvas('🎮 Play Me!')),
                    transparent: true,
                });
                const label = new THREE.Sprite(spriteMaterial);
                label.position.set(0, 6.6, 0); // adjust height
                label.scale.set(2.5, 1.2, 1);
                label.name = 'arcadeLabel';
                arcadeModel.add(label);

                // --- Animation setup ---
                const clock = new THREE.Clock();
                const baseY = label.position.y;

                function animateLabel() {
                    requestAnimationFrame(animateLabel);
                    const elapsed = clock.getElapsedTime();
                    // Smooth up-down motion using sine wave
                    label.position.y = baseY + Math.sin(elapsed * 1.5) * 0.1; 
                    // ↑ 1.5 = speed multiplier, 0.2 = motion amplitude
                }
                animateLabel();


                // Add to the scene
                scene.add(arcadeModel);
            },
            (xhr) => console.log((xhr.loaded / xhr.total) * 100 + '% loaded'),
            (error) => console.error('Error loading arcade model:', error)
        );
}
