/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: BertO (https://sketchfab.com/bertosalotti)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/soho-bed-3d-model-97e361e8beda4112ac5b1b5bcd388cdf
Title: Soho bed - 3D Model
*/
'use client';
import { GLTFLoader } from "three/examples/jsm/Addons.js";
import * as THREE from 'three';

export function BedModel(scene: THREE.Scene) {
    const loader = new GLTFLoader();
    let bedBoundingBox: THREE.Box3 | null = null;

    loader.load(
        '/assets/3d/soho_bed.glb', // relative to your `public/` folder
        (gltf) => {
            const bedModel = gltf.scene;
            bedModel.position.set(-4.4, 0, 4.2); // matches your old bed’s position
            bedModel.scale.set(1.5, 1.5, 1.5);
            bedModel.rotation.y = Math.PI; // rotate if needed

            bedModel.traverse((child) => {
                if ((child as THREE.Mesh).isMesh) {
                child.castShadow = true;
                child.receiveShadow = true;
                }
            });

            scene.add(bedModel);

            // Calculate bounding box for collision
            bedBoundingBox = new THREE.Box3().setFromObject(bedModel);

            // Add some padding to the bounding box
            bedBoundingBox.expandByScalar(0.3);
        },
        (xhr) => console.log(`Bed model: ${(xhr.loaded / xhr.total) * 100}% loaded`),
        (error) => console.error('Error loading bed model:', error)
    );

        // Return collision check function
    return {
        checkCollision: (position: THREE.Vector3): boolean => {
            if (!bedBoundingBox) return false;
            return bedBoundingBox.containsPoint(position);
        },
        getBoundingBox: () => bedBoundingBox
    };
}