/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: KenShi_ (https://sketchfab.com/KenShi3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-setup-129b010fb05a44e8a85497178e2dd5b3
Title: Computer Setup
*/

'use client';

import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';


const addSetupLighting = (model: THREE.Object3D) => {
    // Compute model bounds
    const box = new THREE.Box3().setFromObject(model);
    const center = box.getCenter(new THREE.Vector3());
    const size = box.getSize(new THREE.Vector3());

    // Accent light behind the model
    const accent = new THREE.PointLight(0xff00FFFF, .1, size.z * 6);
    
    // Behind = negative Z in model space
    accent.position.set(
        center.x,
        center.y + size.y * .6,
        center.z - size.z * -0.001
    );

    model.add(accent);
};

export function ComputerSet(scene: THREE.Scene, modalKey : string) {
    const loader = new GLTFLoader();

    const createTextCanvas = (text: string) => {
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d')!;

        canvas.width = 512;
        canvas.height = 256;

        ctx.font = 'bold 64px Arial';
        ctx.fillStyle = '#000000';
        ctx.textAlign = 'center';
        ctx.textBaseline = 'middle';
        ctx.shadowColor = '#00FFFF';
        ctx.shadowBlur = 12;

        ctx.fillText(text, canvas.width / 2, canvas.height / 2);
        return canvas;
    };

    loader.load(
        '/assets/3d/computer_setup.glb',
        (gltf) => {
            const model = gltf.scene;
            addSetupLighting(model);

            // Model transform
            model.position.set(2.75, 0, -0.005);
            model.rotation.y = 3.055;
            model.scale.set(1, 1, 1);

            // Enable shadows
            model.traverse((child) => {
                if ((child as THREE.Mesh).isMesh) {
                    child.castShadow = true;
                    child.receiveShadow = true;
                    child.userData.section = modalKey;
                }
            });

            const material = new THREE.SpriteMaterial({
                map: new THREE.CanvasTexture(createTextCanvas('👩🏻‍💻 My Works')),
                transparent: true,
            });

            const label = new THREE.Sprite(material);
            label.position.set(-2.8, 2, -1.7); // adjust height
            label.scale.set(1, .8, .8);
            label.name = 'myWorksLabel';
            model.add(label);

            // --- Animation setup ---
            const clock = new THREE.Clock();
            const baseY = label.position.y

            function animateLabel() {
                requestAnimationFrame(animateLabel);
                const elapsed = clock.getElapsedTime();
                // Smooth up-down motion using sine wave
                label.position.y = baseY + Math.sin(elapsed * 1) * 0.1; 
                // ↑ 1.5 = speed multiplier, 0.2 = motion amplitude
            }
            animateLabel();

            scene.add(model);
        },
        undefined,
        (error) => {
            console.error('Error loading Spiderman model:', error);
        }
    );
}
