/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: hugannh3 (https://sketchfab.com/hugannh3)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spiderman-50f26cc035454aa6820ff695a1c769d0
Title: Spiderman
*/
'use client';

import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';


const addSetupLighting = (model: THREE.Object3D) => {
    const ambient = new THREE.PointLight(0xffD22B2B, .75, 2);
    ambient.position.set(0, .25, 0);
    model.add(ambient);

    const accent = new THREE.PointLight(0xffD22B2B, .3, 1.5);
    accent.position.set(0, 0.1, 0);
    model.add(accent);
};

export function Spiderman(scene: THREE.Scene, modalKey : string) {
    const loader = new GLTFLoader();

    const createTextCanvas = (text: string) => {
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d')!;

        canvas.width = 512;
        canvas.height = 256;

        ctx.font = 'bold 64px Arial';
        ctx.fillStyle = '#000000';
        ctx.textAlign = 'center';
        ctx.textBaseline = 'middle';
        ctx.shadowColor = '#D22B2B';
        ctx.shadowBlur = 12;

        ctx.fillText(text, canvas.width / 2, canvas.height / 2);
        return canvas;
    };

    loader.load(
        '/assets/3d/spiderman.glb',
        (gltf) => {
            const model = gltf.scene;

            // Model transform
            model.position.set(5.2, 0, -5);
            model.rotation.y = Math.PI / -3;
            model.scale.set(7.5, 7, 7.5);

            // Enable shadows
            model.traverse((child) => {
                if ((child as THREE.Mesh).isMesh) {
                    child.castShadow = true;
                    child.receiveShadow = true;
                    child.userData.section = modalKey;
                }
            });

            const aboutMaterial = new THREE.SpriteMaterial({
                map: new THREE.CanvasTexture(createTextCanvas('🧑 About Me')),
                transparent: true,
            });

            const label = new THREE.Sprite(aboutMaterial);
            label.position.set(0, .32, 0); // adjust height
            label.scale.set(.14, .1, .4);
            label.name = 'aboutMeLabel';
            model.add(label);
            addSetupLighting(model);
            // --- Animation setup ---
            const clock = new THREE.Clock();
            const baseY = label.position.y;

            function animateLabel() {
                requestAnimationFrame(animateLabel);
                const elapsed = clock.getElapsedTime();
                // Smooth up-down motion using sine wave
                label.position.y = baseY + Math.sin(elapsed * 1) * 0.01; 
                // ↑ 1.5 = speed multiplier, 0.2 = motion amplitude
            }
            animateLabel();

            scene.add(model);
        },
        undefined,
        (error) => {
            console.error('Error loading Spiderman model:', error);
        }
    );
}
